<a href="https://colab.research.google.com/github/annuu1101/module22/blob/main/data_structure_fundamentals_Oct042023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
li = [1,2,3,44,5,9]


In [ ]:
type(li)

list

In [ ]:
list((1,2,3,3,4,5,6))

[1, 2, 3, 3, 4, 5, 6]

In [ ]:
tuple((1,5,2,2,3,4))

(1, 5, 2, 2, 3, 4)

In [ ]:
import array

In [ ]:
first_arr = array.array('i',[1,2,3,45,89])

In [ ]:
type(first_arr)

array.array

In [ ]:
first_arr = array.array([1,2,3,45,89])

TypeError: ignored

In [ ]:
second_arr = array.array("I",[1,2,3,45,89])

In [ ]:
second_arr

array('I', [1, 2, 3, 45, 89])

In [ ]:
second_arr = array.array("I",[-1,2,3,45,89])

OverflowError: ignored

In [ ]:
['a','b','c']
'abc'

In [ ]:
second_arr = array.array("u",['a','b','c'])

In [ ]:
second_arr

array('u', 'abc')

In [ ]:
second_arr[0]

'a'

In [ ]:
array.array("B",['a','b','cg'])

TypeError: ignored

In [ ]:
import numpy

In [ ]:
numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
numpy.array([1,2,3,4,5,'b'])

array(['1', '2', '3', '4', '5', 'b'], dtype='<U21')

In [ ]:
numpy.array([1,2,3,4,5,'abCdfj'])

array(['1', '2', '3', '4', '5', 'abCdfj'], dtype='<U21')

In [ ]:
[1,2,3,4,5,8.6,8.9,1.9,100]

[1, 2, 3, 4, 5, 8.6, 8.9, 1.9, 100]

In [ ]:
numpy.array([1,2,3,4,5,8.6,8.9,1.9,100])

array([  1. ,   2. ,   3. ,   4. ,   5. ,   8.6,   8.9,   1.9, 100. ])

In [ ]:
a = numpy.array([1,2,3,4,5,8.6,8.9,1.9,100,False])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(10,)

In [ ]:
a.ndim

1

In [ ]:
numpy.array([1.0,True,False])

array([1., 1., 0.])

In [ ]:
set((1,2,3,4,5,5))

{1, 2, 3, 4, 5}

In [ ]:
# multi dimension arrays

In [ ]:
import numpy as np

In [ ]:
b = np.array([[1,2,3,4],[3,4,5,6]])

In [ ]:
b

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [ ]:
b.ndim

2

In [ ]:
c = np.array([[1,2,3,4],[3,4,5,6],[1,2,3,4]])

In [ ]:
c.ndim

2

In [ ]:
for i in c:
  print(i)

[1 2 3 4]
[3 4 5 6]
[1 2 3 4]


In [ ]:
c[0][-1]

4

In [ ]:
c[0]

array([1, 2, 3, 4])

In [ ]:
## 3d

In [ ]:
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [ ]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
d.ndim

3

In [ ]:
d.shape

(3, 2, 3)

In [ ]:
e = np.array([[[1,2,3,4],[4,5,6,5]],[[1,2,3,8],[4,5,6,9]],[[1,2,3,10],[4,5,7,6]]])

In [ ]:
e.shape

(3, 2, 4)

In [ ]:
f = np.array([1,2,3,4,5,5])

In [ ]:
np.delete(f,2)

array([1, 2, 4, 5, 5])

In [ ]:
e

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  5]],

       [[ 1,  2,  3,  8],
        [ 4,  5,  6,  9]],

       [[ 1,  2,  3, 10],
        [ 4,  5,  7,  6]]])

In [ ]:
np.delete(e,-1)

array([ 1,  2,  3,  4,  4,  5,  6,  5,  1,  2,  3,  8,  4,  5,  6,  9,  1,
        2,  3, 10,  4,  5,  7])

In [ ]:
g = np.array([12312,21,4.351,5,1353.513,5515,12515,1515,1])

In [ ]:
g

array([1.231200e+04, 2.100000e+01, 4.351000e+00, 5.000000e+00,
       1.353513e+03, 5.515000e+03, 1.251500e+04, 1.515000e+03,
       1.000000e+00])

In [ ]:
np.sort(g)

array([1.000000e+00, 4.351000e+00, 5.000000e+00, 2.100000e+01,
       1.353513e+03, 1.515000e+03, 5.515000e+03, 1.231200e+04,
       1.251500e+04])

In [ ]:
12312 in g

True

In [ ]:
np.where(g== 5)[0][0]

3